---
- name: Install nginx with vhosts
  hosts: webservers
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
      - "test.com"
      - "orange.com"
      - "hoogle.com"

  roles:
    - nginx-vhosts
